### ISSUE TITLE
best_checkpoint

### ISSUE THREAD

**Issue by Lirain21** [Wenlin-Chen/FS-Mol-ADKF-IFT#7]
Could you please provide the best-checkpoint of PAR and ADKF-IFT? I have some trouble reproducing main experiment

**Comment by Wenlin-Chen** [comment]
Hi! As described in REAME, the best checkpoints of ADKF-IFT (both classification and regression) can be found [here](https://figshare.com/articles/online_resource/adkf-ift-weights_zip/22070105). Unfortunately, the best checkpoint of PAR was not saved but you should be able to reproduce the results using our code. Could you describe the issues that you encountered when reproducing the results?

**Comment by Lirain21** [comment]
Thank you so much for the best checkpoints of ADKF-IFT. I will try to reproduce the results of PAR.
